"""Static editable config center sections."""

from __future__ import annotations

from typing import Any

from web.api.config_schema.fields import field


BASE_SECTIONS: list[dict[str, Any]] = [
    {
        "key": "signal_selection",
        "label": "全局选股门槛",
        "description": "所有策略共享的 Top-N、最低分和买入数量默认值；策略级覆盖在下方独立展示。",
        "group": "strategy_management",
        "subgroup": "strategy_selection",
        "subgroup_label": "策略级选股门槛",
        "order": 100,
        "fields": [
            field("top_pct", "Top 百分比", "float", min_val=0.001, max_val=1.0, default=0.05),
            field("min_buys", "最小买入数", "int", min_val=0, max_val=100, default=5),
            field("max_buys", "最大买入数", "int", min_val=1, max_val=500, default=80),
            field("min_score", "默认最低分", "float", min_val=0, max_val=100, default=50),
        ],
    },
    {
        "key": "buffett.margin_of_safety",
        "label": "巴菲特 · 安全边际",
        "description": "DCF 折现、永续增长和安全边际参数",
        "group": "strategy_management",
        "subgroup": "strategy_buffett",
        "subgroup_label": "巴菲特价值策略",
        "order": 300,
        "fields": [
            field("dcf_discount_rate", "DCF折现率", "float", min_val=0.03, max_val=0.20, default=0.08),
            field("growth_rate_terminal", "永续增长率", "float", min_val=0.01, max_val=0.10, default=0.03),
            field("safety_margin_pct", "安全边际要求", "float", min_val=0.1, max_val=0.6, default=0.30),
        ],
    },
    {
        "key": "buffett.moat",
        "label": "巴菲特 · 护城河阈值",
        "description": "ROE、毛利率和资产负债过滤阈值；金融行业特殊阈值仍在 YAML 中维护。",
        "group": "strategy_management",
        "subgroup": "strategy_buffett",
        "subgroup_label": "巴菲特价值策略",
        "order": 310,
        "fields": [
            field("min_roe", "最低ROE", "float", min_val=0, max_val=1, default=0.15),
            field("min_roe_years", "ROE历史年数", "int", min_val=1, max_val=10, default=5),
            field("min_gross_margin", "最低毛利率", "float", min_val=0, max_val=1, default=0.30),
            field("max_debt_equity", "最高资产负债比", "float", min_val=0, max_val=5, default=1.5),
        ],
    },
    {
        "key": "buffett.scoring",
        "label": "巴菲特 · 评分权重",
        "description": "ROE、安全边际和利润率等质量项的评分权重与封顶值。",
        "group": "strategy_management",
        "subgroup": "strategy_buffett",
        "subgroup_label": "巴菲特价值策略",
        "order": 320,
        "fields": [
            field("weight_roe", "ROE权重", "float", min_val=0, max_val=100, default=30),
            field("weight_safety", "安全边际权重", "float", min_val=0, max_val=100, default=50),
            field("weight_margin", "利润率权重", "float", min_val=0, max_val=100, default=20),
            field("cap_roe", "ROE封顶", "float", min_val=0, max_val=1, default=0.25),
            field("cap_safety", "安全边际封顶", "float", min_val=0, max_val=1, default=0.5),
            field("cap_margin", "利润率封顶", "float", min_val=0, max_val=1, default=0.6),
        ],
    },
    {
        "key": "buffett.valuation",
        "label": "巴菲特 · 估值扩展",
        "description": "DCF 高增长期、默认增长率和终值估算参数",
        "group": "strategy_management",
        "subgroup": "strategy_buffett",
        "subgroup_label": "巴菲特价值策略",
        "order": 330,
        "fields": [
            field("growth_period", "DCF增长期(年)", "int", min_val=3, max_val=10, default=5),
            field("terminal_pe", "终值PE倍数", "float", min_val=5, max_val=50, default=20),
            field("growth_default", "默认增长率", "float", min_val=0, max_val=0.2, default=0.05),
            field("growth_min", "增长率下限", "float", min_val=0, max_val=0.2, default=0.03),
            field("growth_max", "增长率上限", "float", min_val=0, max_val=0.3, default=0.12),
            field("fcf_fallback_ratio", "FCF回退比例", "float", min_val=0, max_val=1, default=0.7),
        ],
    },
    {
        "key": "signals.multifactor",
        "label": "多因子 · 总权重",
        "description": "五维复合评分权重和最低买入评分",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 400,
        "fields": [
            field("buy_threshold", "买入阈值", "float", min_val=0, max_val=100, default=52),
            field("weights.quality", "质量权重", "float", min_val=0, max_val=1, default=0.35),
            field("weights.valuation", "估值权重", "float", min_val=0, max_val=1, default=0.25),
            field("weights.technical", "技术权重", "float", min_val=0, max_val=1, default=0.15),
            field("weights.market", "市场权重", "float", min_val=0, max_val=1, default=0.10),
            field("weights.industry_momentum", "行业动量权重", "float", min_val=0, max_val=1, default=0.15),
        ],
    },
    {
        "key": "signals.multifactor.quality",
        "label": "多因子 · 质量项",
        "description": "质量评分中 Buffett 分数、ROE 和趋势加减分参数",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 410,
        "fields": [
            field("buffett_weight", "Buffett质量权重", "float", min_val=0, max_val=1, default=0.6),
            field("roe_cap", "ROE封顶分", "float", min_val=0, max_val=100, default=30),
            field("roe_multiplier", "ROE乘数", "float", min_val=0, max_val=10, default=1.2),
            field("trend_bonus_up", "ROE上升加分", "float", min_val=-20, max_val=20, default=5),
            field("trend_bonus_down", "ROE下降扣分", "float", min_val=-20, max_val=20, default=-5),
        ],
    },
    {
        "key": "signals.multifactor.valuation",
        "label": "多因子 · 估值项",
        "description": "深度、适中和轻度低估的分层阈值与得分",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 420,
        "fields": [
            field("tier_deep_value", "深度低估阈值", "float", min_val=0, max_val=1, default=0.5),
            field("tier_moderate_value", "适中低估阈值", "float", min_val=0, max_val=1, default=0.3),
            field("tier_slight_value", "轻度低估阈值", "float", min_val=0, max_val=1, default=0.15),
            field("score_deep", "深度低估得分", "float", min_val=0, max_val=100, default=80),
            field("score_moderate", "适中低估得分", "float", min_val=0, max_val=100, default=60),
            field("score_slight", "轻度低估得分", "float", min_val=0, max_val=100, default=40),
        ],
    },
    {
        "key": "signals.multifactor.technical",
        "label": "多因子 · 技术项",
        "description": "动量、波动和技术分布的默认参数",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 430,
        "fields": [
            field("weight_momentum", "动量权重", "float", min_val=0, max_val=1, default=0.6),
            field("weight_volatility", "波动权重", "float", min_val=0, max_val=1, default=0.4),
            field("mom_strong", "强动量阈值", "float", min_val=0, max_val=1, default=0.15),
            field("mom_multiplier_strong", "强动量乘数", "float", min_val=0, max_val=1000, default=400),
            field("mom_multiplier_normal", "普通动量乘数", "float", min_val=0, max_val=1000, default=200),
            field("vol_max_score", "波动最高分", "float", min_val=0, max_val=100, default=30),
            field("vol_penalty_mult", "波动扣分乘数", "float", min_val=0, max_val=500, default=100),
            field("default_volatility", "默认波动率", "float", min_val=0, max_val=2, default=0.3),
        ],
    },
    {
        "key": "signals.multifactor.industry",
        "label": "多因子 · 行业动量",
        "description": "行业 20/60 日动量融合和得分上下限",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 440,
        "fields": [
            field("weight_20d", "20日权重", "float", min_val=0, max_val=1, default=0.6),
            field("weight_60d", "60日权重", "float", min_val=0, max_val=1, default=0.4),
            field("base", "基础分", "float", min_val=0, max_val=100, default=50),
            field("multiplier", "动量乘数", "float", min_val=0, max_val=1000, default=250),
            field("cap_high", "得分上限", "float", min_val=0, max_val=100, default=80),
            field("cap_low", "得分下限", "float", min_val=0, max_val=100, default=20),
        ],
    },
    {
        "key": "signals.multifactor.momentum",
        "label": "多因子 · 动量窗口",
        "description": "多因子策略动量评分参数",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 450,
        "fields": [
            field("weight_3m", "3月动量权重", "float", min_val=0, max_val=1, default=0.35),
            field("weight_6m", "6月动量权重", "float", min_val=0, max_val=1, default=0.65),
            field("strong_threshold", "强势阈值", "float", min_val=0.05, max_val=0.5, default=0.15),
            field("strong_score", "强势评分", "float", min_val=0, max_val=100, default=40),
            field("multiplier_strong", "强势乘数", "float", min_val=50, max_val=1000, default=400),
            field("multiplier_normal", "正常乘数", "float", min_val=50, max_val=1000, default=200),
            field("weak_floor", "弱势底线", "float", min_val=0, max_val=50, default=20),
        ],
    },
    {
        "key": "signals.multifactor.trend_penalty",
        "label": "多因子 · 趋势惩罚",
        "description": "下跌趋势对动量评分的惩罚",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 460,
        "fields": [
            field("threshold", "惩罚阈值", "float", min_val=-0.5, max_val=0, default=-0.05),
            field("multiplier", "惩罚乘数", "float", min_val=0.1, max_val=1.0, default=0.55),
        ],
    },
    {
        "key": "signals.multifactor.roe_trend",
        "label": "多因子 · ROE趋势",
        "description": "ROE 趋势分类参数",
        "group": "strategy_management",
        "subgroup": "strategy_multifactor",
        "subgroup_label": "多因子策略",
        "order": 470,
        "fields": [
            field("up_threshold", "上升阈值", "float", min_val=1.0, max_val=1.5, default=1.05),
            field("down_threshold", "下降阈值", "float", min_val=0.5, max_val=1.0, default=0.95),
            field("min_years", "最小年数", "int", min_val=2, max_val=10, default=3),
        ],
    },
    {
        "key": "ml",
        "label": "ML · LightGBM",
        "description": "PIT 特征、Regime 模型和 stale feature 防护参数",
        "group": "strategy_management",
        "subgroup": "strategy_ml",
        "subgroup_label": "机器学习策略",
        "order": 500,
        "fields": [
            field("use_regime_models", "使用Regime模型", "bool", default=True),
            field("score_scale", "分数缩放", "float", min_val=0.1, max_val=20, default=5.0),
            field("max_feature_age_months", "最大特征年龄(月)", "int", min_val=1, max_val=24, default=3),
            field("allow_stale_features", "允许过期特征", "bool", default=False),
            field("allow_live_factor_fallback", "允许实时因子回退", "bool", default=False),
        ],
    },
    {
        "key": "cybernetics.score_weights",
        "label": "Regime · 评分权重",
        "description": "市场状态检测的四维权重 (总和建议100)",
        "group": "market_regime",
        "subgroup": "regime_scoring",
        "subgroup_label": "规则评分",
        "order": 600,
        "fields": [
            field("trend", "趋势权重", "float", min_val=0, max_val=100, default=30),
            field("breadth", "广度权重", "float", min_val=0, max_val=100, default=30),
            field("risk", "风险权重", "float", min_val=0, max_val=100, default=30),
            field("volume", "量能权重", "float", min_val=0, max_val=100, default=10),
        ],
    },
    {
        "key": "cybernetics.breadth_weights",
        "label": "Regime · 广度强度",
        "description": "市场广度强度计算公式权重",
        "group": "market_regime",
        "subgroup": "regime_scoring",
        "subgroup_label": "规则评分",
        "order": 610,
        "fields": [
            field("advance_ratio", "上涨比例权重", "float", min_val=0, max_val=1, default=0.35),
            field("above_ma20", "MA20上方权重", "float", min_val=0, max_val=1, default=0.30),
            field("above_ma60", "MA60上方权重", "float", min_val=0, max_val=1, default=0.25),
            field("above_ma120", "MA120上方权重", "float", min_val=0, max_val=1, default=0.10),
        ],
    },
    {
        "key": "cybernetics.risk_strength_weights",
        "label": "Regime · 风险强度",
        "description": "风险强度中回撤、波动和下跌压力的组合权重",
        "group": "market_regime",
        "subgroup": "regime_scoring",
        "subgroup_label": "规则评分",
        "order": 620,
        "fields": [
            field("drawdown", "回撤权重", "float", min_val=0, max_val=1, default=0.50),
            field("volatility", "波动权重", "float", min_val=0, max_val=1, default=0.30),
            field("pressure", "下跌压力", "float", min_val=0, max_val=1, default=0.20),
        ],
    },
    {
        "key": "cybernetics.adaptive.detection",
        "label": "Regime · 判定阈值",
        "description": "牛熊阈值、趋势/广度确认、驻留门槛和量能确认阈值",
        "group": "market_regime",
        "subgroup": "regime_detection",
        "subgroup_label": "状态切换",
        "order": 630,
        "fields": [
            field("regime_bull_threshold", "牛市评分阈值", "float", min_val=0, max_val=100, default=60),
            field("regime_bear_threshold", "熊市评分阈值", "float", min_val=0, max_val=100, default=40),
            field("regime_trend_confirm", "牛市趋势确认", "float", min_val=0, max_val=1, default=0.55),
            field("breadth_bull_threshold", "牛市广度确认", "float", min_val=0, max_val=1, default=0.55),
            field("regime_bear_trend_breakdown", "熊市趋势击穿", "float", min_val=0, max_val=1, default=0.40),
            field("breadth_bear_threshold", "熊市广度击穿", "float", min_val=0, max_val=1, default=0.40),
            field("regime_min_dwell", "状态切换最小驻留", "int", min_val=1, max_val=20, default=3),
            field("volume_expansion", "放量阈值", "float", min_val=1.0, max_val=3.0, default=1.20),
            field("volume_contraction", "缩量阈值", "float", min_val=0.1, max_val=1.0, default=0.80),
        ],
    },
    {
        "key": "cybernetics",
        "label": "Regime · HMM与样本",
        "description": "HMM 置信度、缓存、最小数据量等",
        "group": "market_regime",
        "subgroup": "regime_detection",
        "subgroup_label": "状态切换",
        "order": 640,
        "fields": [
            field("hmm_confidence_override", "HMM置信度覆盖阈值", "float", min_val=0.5, max_val=1.0, default=0.80),
            field("min_bars_trend", "趋势最小数据量", "int", min_val=20, max_val=252, default=60),
            field("min_bars_risk", "风险最小数据量", "int", min_val=10, max_val=120, default=30),
        ],
    },
    {
        "key": "risk_control",
        "label": "风控限制",
        "description": "仓位、敞口、单笔、回撤限制",
        "group": "execution_risk",
        "subgroup": "risk_rules",
        "subgroup_label": "交易风控",
        "order": 700,
        "fields": [
            field("max_single_position.max_pct", "单票仓位上限", "float", min_val=0.05, max_val=1.0, default=0.25),
            field("max_total_exposure.max_pct", "总敞口上限", "float", min_val=0.1, max_val=1.0, default=0.80),
            field("max_orders_per_day.max_count", "每日订单上限", "int", min_val=1, max_val=200, default=20),
            field("max_drawdown_circuit_breaker.max_drawdown_pct", "回撤熔断阈值", "float", min_val=-0.50, max_val=-0.05, default=-0.15),
            field("max_single_order_amount.max_amount", "单笔金额上限", "float", min_val=10000, max_val=5000000, default=500000),
        ],
    },
    {
        "key": "paper_trading",
        "label": "PaperBroker 执行",
        "description": "模拟交易资金、下单、撮合和策略执行上限",
        "group": "execution_risk",
        "subgroup": "paper_broker",
        "subgroup_label": "模拟执行",
        "order": 710,
        "fields": [
            field("enabled", "启用模拟交易", "bool", default=True),
            field("initial_cash", "初始资金", "float", min_val=1000, max_val=100000000, default=1000000),
            field("commission_rate", "综合佣金率", "float", min_val=0, max_val=0.01, default=0.00081),
            field("risk_enabled", "启用风控", "bool", default=True),
            field("order_value_pct", "单笔资金比例", "float", min_val=0.001, max_val=1, default=0.05),
            field("max_order_value", "单笔金额上限", "float", min_val=1000, max_val=5000000, default=50000),
            field("max_orders_per_strategy", "每策略订单上限", "int", min_val=1, max_val=100, default=5),
            field("sell_all_on_sell_signal", "卖出信号全平", "bool", default=True),
            field("auto_execute", "自动执行", "bool", default=False),
        ],
    },
    {
        "key": "trading.exchange.stock",
        "label": "A股交易费率",
        "description": "股票交易的印花税、佣金、过户费等",
        "group": "execution_risk",
        "subgroup": "exchange_costs",
        "subgroup_label": "交易费率",
        "order": 720,
        "fields": [
            field("stamp_tax", "印花税", "float", min_val=0, max_val=0.01, default=0.0005, description="卖出单向征收"),
            field("commission", "佣金率", "float", min_val=0, max_val=0.01, default=0.00025, description="双向征收"),
            field("transfer_fee", "过户费率", "float", min_val=0, max_val=0.001, default=0.00001),
            field("min_commission", "最低佣金(元)", "float", min_val=0, max_val=50, default=5.0),
            field("lot_size", "每手股数", "int", min_val=1, max_val=1000, default=100),
        ],
    },
    {
        "key": "backtest",
        "label": "回测参数",
        "description": "回测日期范围、最小数据量、再平衡参数",
        "group": "research_backtest",
        "subgroup": "backtest_runtime",
        "subgroup_label": "回测运行",
        "order": 800,
        "fields": [
            field("start_date", "起始日期", "string", default="2015-01-01"),
            field("end_date", "结束日期", "string", default="2026-05-10"),
            field("min_bars", "最小数据条数", "int", min_val=50, max_val=500, default=200),
            field("min_history", "评分最小历史(天)", "int", min_val=20, max_val=252, default=63),
            field("alpha_min_score", "Alpha最低评分", "float", min_val=0, max_val=100, default=30),
            field("rebalance.drift_threshold", "漂移再平衡阈值", "float", min_val=0.1, max_val=1.0, default=0.75),
            field("rebalance.overlap_threshold", "重叠度阈值", "float", min_val=0.1, max_val=1.0, default=0.50),
            field("rebalance.max_idle_days", "最大空闲天数", "int", min_val=7, max_val=365, default=28),
        ],
    },
    {
        "key": "data.fetcher",
        "label": "数据获取",
        "description": "API 请求节流、重试、缓存参数",
        "group": "data_ops",
        "subgroup": "fetcher",
        "subgroup_label": "获取与缓存",
        "order": 900,
        "fields": [
            field("min_interval", "请求最小间隔(秒)", "float", min_val=0.5, max_val=30, default=3.0),
            field("jitter_max", "抖动最大值(秒)", "float", min_val=0, max_val=5, default=0.5),
            field("max_retries", "最大重试次数", "int", min_val=0, max_val=10, default=3),
            field("base_delay", "退避基础延迟(秒)", "float", min_val=0.5, max_val=30, default=2.0),
            field("backoff_factor", "退避倍数", "float", min_val=1.0, max_val=10, default=2.0),
            field("jitter_ratio", "退避抖动比例", "float", min_val=0, max_val=1, default=0.3),
            field("mem_cache_max", "内存缓存条目上限", "int", min_val=8, max_val=1024, default=64),
            field("ttl_daily_hours", "日线缓存TTL(小时)", "int", min_val=1, max_val=168, default=24),
            field("ttl_realtime_hours", "实时缓存TTL(小时)", "int", min_val=0, max_val=24, default=1),
            field("socket_timeout", "网络超时(秒)", "int", min_val=5, max_val=120, default=30),
        ],
    },
    {
        "key": "data_cleaning",
        "label": "数据清洗",
        "description": "OHLCV 清洗规则参数",
        "group": "data_ops",
        "subgroup": "cleaning",
        "subgroup_label": "质量规则",
        "order": 910,
        "fields": [
            field("outlier_detection.sigma", "异常值标准差", "float", min_val=1, max_val=10, default=5),
            field("outlier_detection.max_daily_change_pct", "最大日涨跌幅", "float", min_val=0.05, max_val=0.50, default=0.20),
            field("suspended_detection.max_flat_days", "停牌判定天数", "int", min_val=5, max_val=120, default=60),
            field("missing_value.max_forward_fill", "前向填充天数", "int", min_val=1, max_val=20, default=5),
            field("winsorize.lower_pct", "缩尾下限", "float", min_val=0.001, max_val=0.10, default=0.01),
            field("winsorize.upper_pct", "缩尾上限", "float", min_val=0.90, max_val=0.999, default=0.99),
        ],
    },
    {
        "key": "llm",
        "label": "LLM Provider 路由",
        "description": "通用 LLM provider、use case 和 OpenAI-compatible 调用入口；新增 provider 应扩展 providers.* 并让 use case 指向对应 provider/model。",
        "group": "ai_services",
        "subgroup": "llm_runtime",
        "subgroup_label": "调用路由",
        "order": 990,
        "fields": [
            field("default_provider", "默认 provider", "string", default="deepseek"),
            field("use_cases.factor_hypothesis.provider", "因子发现 provider", "string", default="deepseek"),
            field("use_cases.factor_hypothesis.model", "因子发现模型", "string", default="deepseek-v4-pro"),
            field("providers.deepseek.enabled", "DeepSeek 启用", "bool", default=True),
            field("providers.deepseek.api_key_env", "DeepSeek Key Env", "string", default="DEEPSEEK_API_KEY"),
            field("providers.deepseek.base_url", "DeepSeek Base URL", "string", default="https://api.deepseek.com/v1"),
            field("providers.deepseek.default_model", "DeepSeek 默认模型", "string", default="deepseek-v4-flash"),
            field("providers.deepseek.usage_schema", "DeepSeek 用量范式", "string", default="openai_cache"),
        ],
    },
    {
        "key": "llm.providers.deepseek.pricing",
        "label": "LLM · DeepSeek 定价",
        "description": "DeepSeek provider 的 token 计价参数 (USD/百万token) 及汇率；新增 provider 应在 llm.providers 下扩展。",
        "group": "ai_services",
        "subgroup": "llm_pricing",
        "subgroup_label": "模型成本",
        "order": 1000,
        "fields": [
            field("usd_cny", "USD/CNY 汇率", "float", min_val=5.0, max_val=10.0, default=7.2),
            field("models.deepseek-v4-flash.input_cache_hit", "Flash 缓存命中输入", "float", min_val=0, max_val=1, default=0.0028),
            field("models.deepseek-v4-flash.input_cache_miss", "Flash 计费输入", "float", min_val=0, max_val=5, default=0.14),
            field("models.deepseek-v4-flash.output", "Flash 输出", "float", min_val=0, max_val=5, default=0.28),
            field("models.deepseek-v4-pro.input_cache_hit", "Pro 缓存命中输入", "float", min_val=0, max_val=1, default=0.003625),
            field("models.deepseek-v4-pro.input_cache_miss", "Pro 计费输入", "float", min_val=0, max_val=5, default=0.435),
            field("models.deepseek-v4-pro.output", "Pro 输出", "float", min_val=0, max_val=5, default=0.87),
        ],
    },
]
